package scaffold

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
	"time"

	"salvage.sh/internal/config"
)

func ptrStr(s string) *string   { return &s }
func ptrF64(f float64) *float64 { return &f }
func ptrDur(d time.Duration) *config.Duration {
	cd := config.Duration(d)
	return &cd
}

func TestRenderRoundTrips(t *testing.T) {
	maxAge := ptrDur(48 * time.Hour)
	cfg := Build(
		"prod-orders-db",
		config.Source{
			Kind:       "pgbackrest",
			Stanza:     "orders",
			RepoVolume: "/srv/pgbackrest",
		},
		config.Restore{
			Image:    "registry.example/postgres-pgbackrest:17",
			Database: "orders",
			User:     "postgres",
			Timeout:  config.Duration(30 * time.Minute),
		},
		[]config.Check{
			{
				Name:     "server_reachable",
				SQL:      "SELECT 1",
				Equals:   ptrStr("1"),
				Severity: "required",
			},
			{
				Name:     "orders_fresh",
				SQL:      "SELECT max(created_at) FROM orders",
				MaxAge:   maxAge,
				Severity: "advisory",
			},
			{
				Name:      "orders_nonempty",
				SQL:       "SELECT count(*) FROM (SELECT 1 FROM orders LIMIT 1) x",
				ExpectMin: ptrF64(1),
				Severity:  "advisory",
			},
		},
		"./salvage-report.json",
	)

	rendered, err := Render(cfg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// Header comment must be present.
	if !bytes.Contains(rendered, []byte("Auto-generated by")) {
		t.Errorf("rendered output missing header comment:\n%s", rendered)
	}
	if !bytes.Contains(rendered, []byte("salvage scaffold")) {
		t.Errorf("rendered output missing scaffold reference in header:\n%s", rendered)
	}

	// Write and re-parse via config.Load.
	dir := t.TempDir()
	path := filepath.Join(dir, "salvage.yaml")
	if err := os.WriteFile(path, rendered, 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := config.Load(path)
	if err != nil {
		t.Fatalf("config.Load on rendered output: %v\n%s", err, rendered)
	}

	// Target identity + type.
	if got.Target.Name != "prod-orders-db" {
		t.Errorf("target.name = %q, want prod-orders-db", got.Target.Name)
	}
	if got.Target.Type != "postgres" {
		t.Errorf("target.type = %q, want postgres", got.Target.Type)
	}

	// Source kind/stanza.
	if got.Target.Source.Kind != "pgbackrest" {
		t.Errorf("source.kind = %q, want pgbackrest", got.Target.Source.Kind)
	}
	if got.Target.Source.Stanza != "orders" {
		t.Errorf("source.stanza = %q, want orders", got.Target.Source.Stanza)
	}
	if got.Target.Source.RepoVolume != "/srv/pgbackrest" {
		t.Errorf("source.repo_volume = %q, want /srv/pgbackrest", got.Target.Source.RepoVolume)
	}

	// Restore image.
	if got.Target.Restore.Image != "registry.example/postgres-pgbackrest:17" {
		t.Errorf("restore.image = %q", got.Target.Restore.Image)
	}

	// Checks survive with severities and expectations.
	if len(got.Target.Checks) != 3 {
		t.Fatalf("got %d checks, want 3", len(got.Target.Checks))
	}

	reachable := got.Target.Checks[0]
	if reachable.Name != "server_reachable" || reachable.Severity != "required" {
		t.Errorf("check[0] = %+v, want required server_reachable", reachable)
	}
	if reachable.Equals == nil || *reachable.Equals != "1" {
		t.Errorf("check[0].equals = %v, want \"1\"", reachable.Equals)
	}

	fresh := got.Target.Checks[1]
	if fresh.Name != "orders_fresh" || fresh.Severity != "advisory" {
		t.Errorf("check[1] = %+v, want advisory orders_fresh", fresh)
	}
	if fresh.MaxAge == nil || fresh.MaxAge.Std() != 48*time.Hour {
		t.Errorf("check[1].max_age = %v, want 48h", fresh.MaxAge)
	}

	nonempty := got.Target.Checks[2]
	if nonempty.Name != "orders_nonempty" || nonempty.Severity != "advisory" {
		t.Errorf("check[2] = %+v, want advisory orders_nonempty", nonempty)
	}
	if nonempty.ExpectMin == nil || *nonempty.ExpectMin != 1 {
		t.Errorf("check[2].expect_min = %v, want 1", nonempty.ExpectMin)
	}
}
