// Package scaffold assembles a config.Config and renders it to YAML for the
// `salvage scaffold` command. The rendered output round-trips through config.Load.
package scaffold

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"

	"salvage.sh/internal/config"
)

// header is prepended to every rendered config. It explains the provenance of
// the file and how a human should treat the auto-generated checks.
const header = `# Auto-generated by ` + "`salvage scaffold`" + `. Review the advisory checks below and
# promote the keepers to ` + "`severity: required`" + `. Edit freely — this is a starting point.
`

// skeletonHeader is prepended to per-stanza configs emitted by `salvage fleet`.
// A skeleton carries only structural checks; the user fills in the database and
// runs `salvage scaffold` against it to generate data-specific checks.
const skeletonHeader = `# Skeleton generated by ` + "`salvage fleet`" + ` for one pgBackRest stanza.
# It carries only structural checks. To generate data-specific checks:
#   1. verify ` + "`restore.database`" + ` names a database that exists in this stanza's cluster
#   2. run ` + "`salvage scaffold -config <this-file>`" + ` to introspect and add checks
`

// Render marshals cfg to YAML, prefixed with a header comment block. config's
// Duration type has a MarshalYAML, so durations render as parseable strings and
// the output round-trips through config.Load.
func Render(cfg *config.Config) ([]byte, error) {
	return render(cfg, header)
}

// RenderSkeleton is Render with the fleet skeleton header (see skeletonHeader).
func RenderSkeleton(cfg *config.Config) ([]byte, error) {
	return render(cfg, skeletonHeader)
}

func render(cfg *config.Config, hdr string) ([]byte, error) {
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("marshal config: %w", err)
	}
	var buf bytes.Buffer
	buf.WriteString(hdr)
	buf.Write(body)
	return buf.Bytes(), nil
}

// Build assembles a *config.Config from the discovered pieces. It fixes
// Target.Type to "postgres" and wires the name, source, restore, checks, and
// report output path into place.
func Build(name string, source config.Source, restore config.Restore, checks []config.Check, reportOut string) *config.Config {
	return &config.Config{
		Target: config.Target{
			Name:    name,
			Type:    "postgres",
			Source:  source,
			Restore: restore,
			Checks:  checks,
		},
		Report: config.Report{
			Out: reportOut,
		},
	}
}
