// Package scaffold assembles a config.Config and renders it to YAML for the
// `salvage scaffold` command. The rendered output round-trips through config.Load.
package scaffold

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"

	"salvage.sh/internal/config"
)

// header is prepended to every rendered config. It explains the provenance of
// the file and how a human should treat the auto-generated checks.
const header = `# Auto-generated by ` + "`salvage scaffold`" + `. Review the advisory checks below and
# promote the keepers to ` + "`severity: required`" + `. Edit freely — this is a starting point.
`

// skeletonHeader is prepended to per-unit configs emitted by `salvage fleet`
// (a pgBackRest stanza, or a restic/borg repository). A skeleton carries only
// structural checks; the user fills in the details and runs `salvage scaffold`
// against it to generate data-specific checks.
const skeletonHeader = `# Skeleton generated by ` + "`salvage fleet`" + ` for one surveyed unit.
# It carries only structural checks. To generate data-specific checks:
#   1. verify the source and ` + "`restore`" + ` settings point at this unit's backup
#   2. run ` + "`salvage scaffold -config <this-file>`" + ` to introspect and add checks
`

// Render marshals cfg to YAML, prefixed with the scaffold header comment block
// plus any extra note lines (each rendered as its own comment line — e.g. the
// spec 0028 R6 truncation note when check generation was capped). config's
// Duration type has a MarshalYAML, so durations render as parseable strings and
// the output round-trips through config.Load.
func Render(cfg *config.Config, notes ...string) ([]byte, error) {
	return render(cfg, header, notes)
}

// RenderSkeleton is Render with the fleet skeleton header (see skeletonHeader).
func RenderSkeleton(cfg *config.Config) ([]byte, error) {
	return render(cfg, skeletonHeader, nil)
}

func render(cfg *config.Config, hdr string, notes []string) ([]byte, error) {
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("marshal config: %w", err)
	}
	var buf bytes.Buffer
	buf.WriteString(hdr)
	for _, n := range notes {
		buf.WriteString("# " + n + "\n")
	}
	buf.Write(body)
	return buf.Bytes(), nil
}

// Build assembles a *config.Config from the discovered pieces, wiring the name,
// engine type, source, restore, checks, and report output path into place.
func Build(name, targetType string, source config.Source, restore config.Restore, checks []config.Check, reportOut string) *config.Config {
	return &config.Config{
		Target: config.Target{
			Name:    name,
			Type:    targetType,
			Source:  source,
			Restore: restore,
			Checks:  checks,
		},
		Report: config.Report{
			Out: reportOut,
		},
	}
}
